export { HuaGaoClient } from './client.js';
export type { HuaGaoClientOptions } from './client.js';

export type {
  // Base
  BaseMessage,
  BaseRequest,
  BaseResponseOk,
  BaseResponseErr,
  BaseResponse,
  // Config
  FileNameMode,
  ImageFormat,
  TiffCompression,
  GlobalConfig,
  SetGlobalConfigRequest,
  GetGlobalConfigResponse,
  // Local image ops
  LoadLocalImageRequest,
  LoadLocalImageResponse,
  SaveLocalImageRequest,
  SaveLocalImageResponse,
  DeleteLocalFileRequest,
  UploadLocalFileRequest,
  MergeLocalImageRequest,
  MergeLocalImageResponse,
  LocalMakeMultiImageRequest,
  LocalMakeMultiImageResponse,
  SplitLocalImageRequest,
  SplitLocalImageResponse,
  LocalMakeZipFileRequest,
  LocalMakeZipFileResponse,
  LocalImageDeskewRequest,
  LocalImageDeskewResponse,
  WatermarkTextPos,
  LocalImageAddWatermarkRequest,
  LocalImageDecontaminationRequest,
  LocalImageDirectionCorrectRequest,
  LocalImageClipRequest,
  LocalImageFadeBkcolorRequest,
  LocalImageAdjustColorsRequest,
  LocalImageBinarizationRequest,
  LocalImageResultResponse,
  // Device
  DeviceParamItem,
  SetDeviceParamRequest,
  DeviceParamInfo,
  DeviceParamDetail,
  GetDeviceParamResponse,
  GetDeviceNameListResponse,
  OpenDeviceRequest,
  GetDeviceSnResponse,
  GetDeviceFwVersionResponse,
  GetCurrDeviceNameResponse,
  StartScanRequest,
  // Device events
  DeviceArriveEvent,
  DeviceRemoveEvent,
  ScanBeginEvent,
  ScanEndEvent,
  ScanInfoEvent,
  ScanImageEvent,
  // Batch / business
  GetBatchIdListResponse,
  OpenBatchRequest,
  DeleteBatchRequest,
  NewBatchRequest,
  NewBatchResponse,
  GetCurrBatchIdResponse,
  ModifyBatchIdRequest,
  BindFolderRequest,
  ImageThumbnail,
  GetImageThumbnailListResponse,
  GetImageCountResponse,
  LoadImageRequest,
  LoadImageResponse,
  SaveImageRequest,
  SaveImageResponse,
  InsertLocalImageRequest,
  InsertImageRequest,
  ModifyImageTagRequest,
  DeleteImageRequest,
  ModifyImageRequest,
  ModifyImageByLocalRequest,
  MoveImageRequest,
  ExchangeImageRequest,
  UploadImageRequest,
  MergeImageRequest,
  MakeMultiImageRequest,
  SplitImageRequest,
  SplitImageResponse,
  MakeZipFileRequest,
  MakeZipFileResponse,
  ImageDeskewRequest,
  ImageDeskewResponse,
  ImageAddWatermarkRequest,
  ImageDecontaminationRequest,
  ImageDirectionCorrectRequest,
  ImageClipRequest,
  ImageFadeBkcolorRequest,
  ImageAdjustColorsRequest,
  ImageBinarizationRequest,
  ImageResultResponse,
  // Unions & maps
  Request,
  Response,
  Event,
  ReceivedMessage,
  FuncName,
  FuncResponseMap,
} from './types.js';
